<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\Service\LanguageManager;
use Cms\View\Icon;

?>

<form class="card" autocomplete="off">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="nav-item"><a class="nav-link active" href="#hotel-room-active" role="tab" data-bs-toggle="tab"><i class="fas fa-hotel"></i> <?= $this->translate('Room'); ?></a></li>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#hotel-room-configuration" role="tab" data-bs-toggle="tab"><i class="fas fa-dice"></i> <?= $this->translate('Configuration'); ?></a></li>
        <?php if (!$new): ?>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#hotel-room-gallery" role="tab" data-bs-toggle="tab"><i class="fas fa-camera-retro"></i> <?= $this->translate('Gallery'); ?> <small class="text-muted">(<?= count($images); ?>)</small></a></li>
        <?php endif; ?>
	</ul>

    <div class="tab-content pt-3">
        <div class="tab-pane fade show active" id="hotel-room-active" role="tabpanel">
            <?php $this->loadPartial('language-tabs'); ?>

            <div class="tab-content">
                <?php foreach ($languages as $index => $language): ?>
                <div class="tab-pane fade <?= $index == 0 ? 'show active' : null; ?>" id="<?= sprintf('language-%s', $language->getId()); ?>" role="tabpanel">
                    <?php $entity = LanguageManager::findByLangId($language->getId(), $room); ?>
                    <?php $this->loadPartial('language-name', ['language' => $language]); ?>

                    <?= Element::hidden(sprintf('translation[%s][id]', $language->getId()), $entity->getId()); ?>
                    <?= Element::hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>
                    <?= Element::hidden(sprintf('translation[%s][web_page_id]', $language->getId()), $entity->getWebPageId()); ?>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Name'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::text(sprintf('translation[%s][name]', $language->getId()), $entity->getName(), ['class' => 'form-control']); ?>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Full description'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][full]', $language->getId()), $entity->getFull(), ['class' => 'form-control']); ?>
                        </div>
                    </div>

                    <div class="row mb-3">
                        <label class="col-lg-2 col-form-label"><?= $this->translate('Description'); ?></label>
                        <div class="col-lg-10">
                            <?= Element::textarea(sprintf('translation[%s][description]', $language->getId()), $entity->getDescription(), ['class' => 'form-control']); ?>
                        </div>
                    </div>

                    <div class="options">
                        <div class="row mb-3">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Slug'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?= Element::text(sprintf('translation[%s][slug]', $language->getId()), $entity->getSlug(), ['class' => 'form-control', 'placeholder' => $this->translate('URL slug for this room. By default is taken from the name')]); ?>

                                    <span class="input-group-text">
                                        <a href="#" data-slug-selector="<?= LanguageManager::generateSelector($language->getId()); ?>"><i class="bi bi-arrow-clockwise" data-bs-toggle="tooltip" title="<?= $this->translate('Refresh'); ?>"></i></a>
                                    </span>
                                </div>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Change frequency'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::select(sprintf('translation[%s][changefreq]', $language->getId()), $this->translateArray($changeFreqs), $entity->getChangeFreq(), ['class' => 'form-select']); ?>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Priority'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::select(sprintf('translation[%s][priority]', $language->getId()), $priorities, $entity->getPriority(), ['class' => 'form-select']); ?>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Title'); ?></label>
                            <div class="col-lg-10">
                                <div class="input-group">
                                    <?= Element::text(sprintf('translation[%s][title]', $language->getId()), $entity->getTitle(), ['class' => 'form-control', 'data-input' => 'title', 'placeholder' => $this->translate('Room title')]); ?>
                                    <span class="input-group-text"><i class="bi bi-pencil"></i></span>
                                </div>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Keywords'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::text(sprintf('translation[%s][keywords]', $language->getId()), $entity->getKeywords(), ['class' => 'form-control', 'placeholder' => $this->translate('Keywords used for search engines')]); ?>
                            </div>
                        </div>

                        <div class="row mb-3">
                            <label class="col-lg-2 col-form-label"><?= $this->translate('Description'); ?></label>
                            <div class="col-lg-10">
                                <?= Element::textarea(sprintf('translation[%s][meta_description]', $language->getId()), $entity->getMetaDescription(), ['class' => 'form-control', 'placeholder' => $this->translate('Meta description for search engines')]); ?>
                            </div>
                        </div>
                    </div>                    
                </div>
                <?php endforeach; ?>
            </div>
        </div>

        <div class="tab-pane fade" id="hotel-room-configuration" role="tabpanel">
            <?= Element::hidden('room[id]', $entity->getId()); ?>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Price per night'); ?></label>
                <div class="col-lg-10">
                    <?= Element::number('room[price]', $entity->getPrice(), ['class' => 'form-control']); ?>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Maximal adults capacity'); ?></label>
                <div class="col-lg-10">
                    <?= Element::number('room[adults]', $entity->getAdults(), ['class' => 'form-control', 'min' => 1]); ?>
                </div>
            </div>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Maximal children capacity'); ?></label>
                <div class="col-lg-10">
                    <?= Element::number('room[children]', $entity->getChildren(), ['class' => 'form-control', 'min' => 0]); ?>
                </div>
            </div>

            <?php if ($entity->getCover()): ?>
            <p>
                <img class="img-fluid" src="<?= $entity->getImageBag()->getUrl('400x400'); ?>" />
            </p>
            <?php endif; ?>

            <div class="row mb-3">
                <label class="col-lg-2 col-form-label"><?= $this->translate('Room cover'); ?></label>
                <div class="col-lg-10">
                    <?= Element::file('room[cover]', 'image/*', ['class' => 'form-control']); ?>
                </div>
            </div>
        </div>

        <?php if (!$new): ?>
        <!-- Gallery -->
        <div class="tab-pane fade" id="hotel-room-gallery" role="tabpanel">
            <p><a class="btn btn-primary" href="<?= $this->url('Hotel:Admin:Gallery@addAction', $entity->getId()); ?>"><i class="fas fa-camera-retro"></i> <?= $this->translate('Upload new image'); ?></a></p>

            <?= $this->widget(new GridViewWidget($images, [
                'tableClass' => 'table table-bordered',
                'columns' => [
                    [
                        'column' => 'file',
                        'label' => 'Image',
                        'value' => function($image){
                            return Element::image($image->getImageBag()->getUrl('400x400'), ['class' => 'img-fluid']);
                        }
                    ],

                    [
                        'column' => 'order',
                        'label' => 'Sorting order'
                    ]
                ],

                'actions' => [
                    function($image){
                        return Icon::edit(
                            $this->url('Hotel:Admin:Gallery@editAction', $image->getId()),
                            $this->translate('Edit this image')
                        );
                    },

                    function($image){
                        return Icon::remove(
                            $this->url('Hotel:Admin:Gallery@deleteAction', $image->getId()),
                            $this->translate('Delete this image')
                        );
                    }
                ]
            ])); ?>
        </div>
        <?php endif; ?>
    </div>

    <?php $this->loadPartial('actions', [
        'new' => !$entity->getId(),
        'add' => 'Hotel:Admin:Room@addAction',
        'edit' => 'Hotel:Admin:Room@editAction',
        'save' => 'Hotel:Admin:Room@saveAction',
        'cancel' => 'Hotel:Admin:Room@indexAction',
        'options' => true
    ]); ?>
</form>