<?php

use Krystal\Form\Element;
use Krystal\Widget\GridView\GridViewWidget;
use Cms\Service\LanguageManager;
use Cms\View\Icon;

defined('KRYSTAL') or die;

?>

<form class="card" data-group="room" autocomplete="off">
    <ul class="nav nav-tabs" role="tablist">
        <li role="presentation" class="nav-item active"><a class="nav-link" href="#hotel-room-active" role="tab" data-toggle="tab"><i class="fas fa-hotel"></i> <?php $this->show('Room'); ?></a></li>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#hotel-room-configuration" role="tab" data-toggle="tab"><i class="fas fa-dice"></i> <?php $this->show('Configuration'); ?></a></li>
        <?php if (!$new): ?>
        <li role="presentation" class="nav-item"><a class="nav-link" href="#hotel-room-gallery" role="tab" data-toggle="tab"><i class="fas fa-camera-retro"></i> <?php $this->show('Gallery'); ?> <small class="text-muted">(<?= count($images); ?>)</small></a></li>
        <?php endif; ?>
	</ul>

    <div class="tab-content">
        <div class="tab-pane fade in active" id="hotel-room-active" role="tabpanel">
            <?php $this->loadPartial('language-tabs'); ?>

            <div class="tab-content">
                <?php foreach ($languages as $index => $language): ?>
                <div class="tab-pane fade in <?php echo $index == 0 ? 'active show' : null; ?>" id="<?php printf('language-%s', $language->getId()); ?>" role="tabpanel">
                    <?php $entity = LanguageManager::findByLangId($language->getId(), $room); ?>
                    <?php $this->loadPartial('language-name', array('language' => $language)); ?>

                    <?= $this->field()->hidden(sprintf('translation[%s][name]', $language->getId()), $entity->getId()); ?>
                    <?= $this->field()->hidden(sprintf('translation[%s][lang_id]', $language->getId()), $language->getId()); ?>
                    <?= $this->field('Name')->text(sprintf('translation[%s][name]', $language->getId()), $entity->getName(), ['class' => 'form-control']); ?>
                    <?= $this->field('Description')->textarea(sprintf('translation[%s][description]', $language->getId()), $entity->getDescription(), ['class' => 'form-control']); ?>
                </div>
                <?php endforeach; ?>
            </div>
        </div>

        <div class="tab-pane fade" id="hotel-room-configuration" role="tabpanel">
            <?= $this->field()->hidden('room[id]', $entity->getId()); ?>
            <?= $this->field('Price per night')->number('room[price]', $entity->getPrice(), ['class' => 'form-control']); ?>
            <?= $this->field('Maximal adults capacity')->number('room[adults]', $entity->getAdults(), ['class' => 'form-control', 'min' => 1]); ?>
            <?= $this->field('Maximal children capacity')->number('room[children]', $entity->getChildren(), ['class' => 'form-control', 'min' => 0]); ?>
        </div>

        <?php if (!$new): ?>
        <!-- Gallery -->
        <div class="tab-pane fade" id="hotel-room-gallery" role="tabpanel">
            <p><a class="btn btn-primary" href="<?= $this->url('Hotel:Admin:Gallery@addAction', $entity->getId()); ?>"><i class="fas fa-camera-retro"></i> <?php $this->show('Upload new image'); ?></a></p>

            <?= $this->widget(new GridViewWidget($images, [
                'tableClass' => 'table table-hover table-bordered table-striped table-sm',
                'columns' => [
                    [
                        'column' => 'file',
                        'value' => function($image){
                            return Element::image($image->getImageBag()->getUrl('400x400'), ['class' => 'img-fluid']);
                        }
                    ],

                    [
                        'column' => 'order',
                        'label' => 'Sorting order'
                    ]
                ],

                'actions' => [
                    function($image){
                        return Icon::edit(
                            $this->url('Hotel:Admin:Gallery@editAction', $image->getId()),
                            $this->translate('Edit this image')
                        );
                    },

                    function($image){
                        return Icon::remove(
                            $this->url('Hotel:Admin:Gallery@deleteAction', $image->getId()),
                            $this->translate('Delete this image')
                        );
                    }
                ]
            ])); ?>
            
        </div>
        <?php endif; ?>
    </div>

    <?php $this->loadPartial('actions', [
        'new' => !$entity->getId(),
        'add' => 'Hotel:Admin:Room@addAction',
        'edit' => 'Hotel:Admin:Room@editAction',
        'save' => 'Hotel:Admin:Room@saveAction',
        'cancel' => 'Hotel:Admin:Room@indexAction'
    ]); ?>
</form>
