<?php

use Krystal\Form\Element;

defined('KRYSTAL') or die;

?>

<form class="card" data-group="image" autocomplete="off">
    <!-- Relational fields -->
    <?= Element::hidden('image[id]', $image->getId()); ?>
    <?= Element::hidden('image[room_id]', $image->getRoomId()); ?>

    <!-- Image data -->
    <div class="form-group row mb-3">
        <label class="col-lg-2 col-form-label"><?= $this->translate('Sorting order'); ?></label>
        <div class="col-lg-10">
            <?= Element::number('image[order]', $image->getOrder(), ['class' => 'form-control']); ?>
        </div>
    </div>

    <?php if ($image->getFile()): ?>
    <p>
        <img class="img-fluid" src="<?= $image->getImageBag()->getUrl('400x400'); ?>" />
    </p>
    <?php endif; ?>

    <div class="form-group row mb-3">
        <label class="col-lg-2 col-form-label"><?= $this->translate('File'); ?></label>
        <div class="col-lg-10">
            <?= Element::file('image[file]', 'image/*', ['class' => 'form-control']); ?>
        </div>
    </div>

    <?php $this->loadPartial('actions', [
        'new' => !$image->getId(),
        'add' => ['Hotel:Admin:Gallery@addAction', $image->getRoomId()],
        'edit' => 'Hotel:Admin:Gallery@editAction',
        'save' => 'Hotel:Admin:Gallery@saveAction',
        'cancel' => ['Hotel:Admin:Room@editAction', $image->getRoomId()]
    ]); ?>
</form>