<?php

use Krystal\Widget\GridView\GridViewWidget;
use Cms\View\Icon;

?>

<div class="btn-toolbar">
    <div class="btn-group mr-2">
        <a class="btn btn-primary" href="<?= $this->url('Hotel:Admin:Room@addAction'); ?>"><i class="fas fa-hotel"></i> <?php $this->show('Add new room'); ?></a>
    </div>

    <div class="btn-group mr-2">
        <a class="btn btn-primary" href="<?= $this->url('Hotel:Admin:Booking@indexAction'); ?>"><i class="fas fa-calendar-alt"></i> <?php $this->show('View all bookings'); ?></a>
    </div>
</div>

<div class="card">
    <div class="table-responsive">
        <?= $this->widget(new GridViewWidget($rooms, [
            'tableClass' => 'table table-hover table-bordered table-striped table-sm',
            'columns' => [
                [
                    'column' => 'id',
                    'label' => '#'
                ],

                [
                    'column' => 'name'
                ],

                [
                    'column' => 'adults',
                    'label' => 'Maximal adults capacity'
                ],

                [
                    'column' => 'children',
                    'label' => 'Maximal children capacity'
                ],

                [
                    'column' => 'price',
                    'label' => 'Price per night',
                    'value' => function($row){
                        return number_format($row['price']);
                    }
                ]
            ],

            'actions' => [
                function($room){
                    return Icon::edit(
                        $this->url('Hotel:Admin:Room@editAction', $room->getId()),
                        $this->translate('Edit this room')
                    );
                },

                function($room){
                    return Icon::remove(
                        $this->url('Hotel:Admin:Room@deleteAction', $room->getId()),
                        $this->translate('Delete this room')
                    );
                }
            ]
        ])); ?>
    </div>
</div>
