<form class="card" data-group="room" autocomplete="off">
    <?= $this->field()->hidden('room[id]', $room->getId()); ?>
    <?= $this->field('Price per night')->number('room[price]', $room->getId(), ['class' => 'form-control']); ?>

    <?php $this->loadPartial('actions', [
        'new' => !$room->getId(),
        'add' => 'Hotel:Admin:Room@addAction',
        'edit' => 'Hotel:Admin:Room@editAction',
        'save' => 'Hotel:Admin:Room@saveAction',
        'cancel' => 'Hotel:Admin:Room@indexAction'
    ]); ?>
</form>